### PR TITLE
update rocm 6.0.0

### PR DESCRIPTION
**Pull request by johnnynunez**
MiOpen is not compatible with +5.5 in windows, but soon

### CODE REVIEW

**Comment by evshiron** [comment]
I wonder if these will work, which seem to be built for ROCm 5.7.0 (as it has a `.570` suffix):

* https://pypi.org/project/tensorflow-rocm/#files

**Comment by johnnynunez** [comment]
> I wonder if these will work, which seem to be built for ROCm 5.7.0 (as it has a `.570` suffix):

I installed them, In my 7900xt says that is not compatible. 

2023-10-31 01:21:04.591507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2015] Ignoring visible gpu device (device: 0, name: Radeon RX 7900 XT, pci bus id: 0000:03:00.0) with AMDGPU version : gfx1100. The supported AMDGPU versions are gfx1030, gfx900, gfx906, gfx908, gfx90a, gfx940, gfx941, gfx942.

**Comment by evshiron** [comment]
> I installed them, In my 7900xt says that is not compatible.

Sigh. It's been so long, and they still haven't included `gfx1100` in the building parameters, even after the official announcement for RX 7900 XTX support. They did add it for MI300s though.

**Comment by johnnynunez** [comment]
> > I installed them, In my 7900xt says that is not compatible.
> 
> Sigh. It's been so long, and they still haven't included `gfx1100` in the building parameters, even after the official announcement for RX 7900 XTX support. They did add it for MI300s though.

In pytorch with pytorch nightly rocm 5.7 is working native without any parameters

**Comment by briansp2020** [comment]
If you build TensorFlow from [source ](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream), it works well on 7900XTX

**Comment by johnnynunez** [comment]
> If you build TensorFlow from [source ](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream), it works well on 7900XTX

The idea is tu build with latest rocm

**Comment by johnnynunez** [comment]
@evshiron I see that in tensorflow v2.14 gfx1100 is in the code, so it's supported because also it use rocm 5.7. Still no wheels.

**Comment by johnnynunez** [comment]
Tensorflow is working now. There is a error in their repositories..
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2290
image

**Pull request closed without merging**
